spring.application.name=maestra-dyd-boot

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

onedrive.tenant-id=${ONEDRIVE_TENANT_ID}
onedrive.client-id=${ONEDRIVE_CLIENT_ID}
onedrive.client-secret=${ONEDRIVE_CLIENT_SECRET}
onedrive.redirect-uri=${ONEDRIVE_REDIRECT_URI}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

aws.region=${AWS_REGION:us-east-2}
aws.s3.bucket=${AWS_S3_BUCKET:documentos-proveedores-dyd}

spring.thymeleaf.cache=false